apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtp-server.fullname" . }}
  labels:
    {{- include "smtp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.smtp.port }}
      targetPort: {{ .Values.service.smtp.port }}
      protocol: TCP
      name: smtp
    - port: {{ .Values.service.management.port }}
      targetPort: {{ .Values.service.management.port }}
      protocol: TCP
      name: http-management
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.port }}
      protocol: TCP
      name: http-webui
  selector:
    {{- include "smtp-server.selectorLabels" . | nindent 4 }}
