# Role
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    # "helm.sh/hook": pre-install
    # "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-4"

---

# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager-role
  namespace: {{ .Release.Namespace }}
  annotations:
    # "helm.sh/hook": pre-install
    # "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-3"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "update"]

---

# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    # "helm.sh/hook": pre-install
    # "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-2"
subjects:
  - kind: ServiceAccount
    name: secret-manager-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager-role
