name: Auto sync from upstream

on:
  schedule:
    - cron: 0 9 * * 1
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.SYNC_UPSTREAM_PAT }}
          fetch-depth: 0
          ref: main

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/eclipse-tractusx/tractus-x-umbrella.git
          git fetch upstream main
      
      - name: Set origin remote with token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.SYNC_UPSTREAM_PAT }}@github.com/ARENA2036/tx-umbrella.git

      - name: Checkout to sync branch
        run: |
          git checkout -b sync-upstream origin/main

      - name: Merge upstream main
        run: |
          set +e
          git merge upstream/main -m "Merge upstream/main into sync-upstream"
          MERGE_STATUS=$?
          if [ $MERGE_STATUS != 0 ]; then
            echo "Conflicts detected"
            git add -A 
            git commit -m "Merge upstream/main into sync-upstream (auto-sync, may contain conflicts)"
          fi
          exit 0
    
      - name: Push sync branch to your fork
        run: |
          git push https://x-access-token:${{ secrets.SYNC_UPSTREAM_PAT }}@github.com/ARENA2036/tx-umbrella.git sync-upstream --force

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Wait for GitHub to register branch
        run: sleep 5

      - name: Verify
        run: |
          git status
          git branch -a

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --repo ARENA2036/tx-umbrella --base main \
          --head sync-upstream \
          --title "Merge sync-upstream to main" \
          --body "This PR rebases main on top of the latest upstream/main." \
          --reviewer "saudkhan116" \
          --reviewer "khanowaisarena"

